[package]
name = "alsa-loopback-latency"
version = "0.1.0"
authors = ["Henry Hoegelow <henry@hoegelow.com>"]
edition = "2018"

[dependencies]
alsa = "0.4.3"
clap = { version = "3.0.9", features = ["derive"] }
rand = "0.8.4"